version: '3.8'
services:
  nextjs:
    build:
      context: .
    ports:
      - "3000:3000"
    container_name: nextjs-container
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
